export default function ProjectVisual({ id }) {
  if (id === 'youxai') return <div className="product-diagram">
    <div className="product-brand">you<span>✳</span>ai<span className="product-caption">THE JOB SEARCH, REIMAGINED.</span></div>
    <div className="browser-diagram"><div className="browser-chrome"><span>● ● ●</span><span>youxai.app</span><span>↗</span></div>
      <div className="browser-content"><span className="diagram-kicker">FROM SEARCH TO YOUR NEXT CHAPTER</span><h4>More possibility.<br/>Less busywork.</h4><div className="pipeline"><span>Discover <b>01</b></span><span>Personalize <b>02</b></span><span>Apply <b>03</b></span></div><div className="local-model"><span className="model-symbol">✳</span><div><strong>AI that stays with you.</strong><span>Gemma 4 E2B · On-device inference</span></div><span className="lock-symbol">↳ LOCAL</span></div></div>
    </div><span className="diagram-note">PRODUCT ARCHITECTURE / BROWSER → LOCAL MODEL</span>
  </div>;
  if (id === 'gemma') return <div className="compute-diagram"><div className="compute-heading"><span>GEMMA 4</span><span>E2B / WEBGPU</span></div><div className="layer-stack">{Array.from({length: 12},(_,i)=><i key={i} style={{'--i':i}}><span>{String(i+1).padStart(2,'0')}</span></i>)}</div><div className="compute-bottom"><span>35 LAYERS<br/><b>15 PRODUCE KV CACHE</b></span><span className="compute-arrow">↗</span></div><span className="diagram-note">HAND-WRITTEN WGSL / ZERO THIRD-PARTY ENGINE CODE</span></div>;
  if (id === 'subgroup') return <div className="debug-diagram"><span className="diagram-kicker">KERNEL COMPARISON / 59 PAIRS</span><div className="kernel-grid">{Array.from({length:59},(_,i)=><i key={i} className={[5,14,26,33,42,54].includes(i)?'divergent':''}/>)}</div><div className="debug-result"><span><i/> 53 MATCHED</span><span><i/> 6 DIVERGENT</span></div><strong>Silent corruption.<br/>Visible evidence.</strong><span className="diagram-note">NVIDIA / WINDOWS · SUBGROUP REDUCTIONS</span></div>;
  if (id === 'context') return <div className="context-diagram"><span className="diagram-kicker">CONTEXT GUARDIAN / LOCAL RETRIEVAL</span><div className="context-flow"><div className="context-pages">{[0,1,2,3].map(i=><i key={i} style={{'--i':i}}>context<br/>────<br/>────<br/>──</i>)}</div><span>→</span><div className="context-core">{'{ }'}<small>RETRIEVE</small></div><span>→</span><div className="context-signal">✳<small>PRECISE<br/>CONTEXT</small></div></div><strong>Give the model<br/>what matters.</strong><span className="diagram-note">MCP · LOCAL EMBEDDINGS · TRANSPARENT PROXY</span></div>;
  return <div className={`meter-diagram meter-${id}`}><span className="diagram-kicker">{id === 'headroom' ? 'HEADROOM / DEVICE BANDWIDTH' : 'WEBLLM BENCH / REPRODUCIBLE REPORTS'}</span><div className="meter-bars">{Array.from({length:28},(_,i)=><i key={i} style={{'--height':`${20+((i*17)%65)}%`,'--i':i}}/>)}</div><div className="meter-axis"><span>{id === 'headroom' ? 'PROBE 01 → 03' : 'LATENCY → DECODE → CONTEXT'}</span><span>MEASURE. UNDERSTAND.</span></div><span className="diagram-note">{id === 'headroom' ? 'THREE INDEPENDENT PROBES / GEMV LADDER' : 'BROWSER-NATIVE / EXPORTABLE JSON'}</span></div>;
}
